### ISSUE TITLE
Your Browser Is Not Supported

### ISSUE THREAD

**Issue by eflernicolas** [timvisee/send#105]
Hi Tim. this will be quite basic question for you:

I'm getting the error "Your Browser Is Not Supported" "send will not work with this browser..." etc

 Steps i did:
- Cloned the github with github desktop.
- On my github directory opened send and ran the commands:
npm install
npm start

Everything seems to run fine, i get:

i ｢wds｣: Project is running at http://0.0.0.0:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\efler\Documents\GitHub\send

But if i enter mi ipv4, then the error happens.

What am i missing? main problem is i can't access with external ip.

**Comment by timvisee** [comment]
This is caused by recent changes in Send. This causes issues when running over a non-HTTPS connection, which is what you're currently having. I'm sorry for that.

This issue should be fixed soon, and if that doesn't work out, I'll revert the changes that are causing this issue.

In the mean time, you may check out an earlier version by running the following command:

```bash
git checkout 625fdf5bca19f75220a7be9c5da1086753972c49
```

Please let me know if that works!

For further details, see this PR/comment: https://github.com/timvisee/send/pull/101#issuecomment-1211095532

**Comment by eflernicolas** [comment]
Tim,
Thanks for that quick answer.

Unfortunately i am still not able to connect through my public ip, while several other programs, fileservers,etc access without problems.

I will wait for the next update and see what happens.

Thank you so much

**Comment by timvisee** [comment]
> Unfortunately i am still not able to connect through my public ip, while several other programs, fileservers,etc access without problems.

Is the correct port open, and, does Send listen on `0.0.0.0`?

**Comment by eflernicolas** [comment]
> > Unfortunately i am still not able to connect through my public ip, while several other programs, fileservers,etc access without problems.
> 
> Is the correct port open, and, does Send listen on `0.0.0.0`?

Tim, thank you again.

Send is listening to 0.0.0.0

Listen Port in config.js inside the Server folder is set to "1443"

I suspect there might be a problem since the command line no matter what i write, says:

Project is running at http://0.0.0.0:8080/

External access is not possible currently.

**Comment by timvisee** [comment]
I've reverted some changes that were causing issues like this.

I've released `v3.4.21`, which should be available once this pipeline succeeds: https://gitlab.com/timvisee/send/-/pipelines/630739924

Please update your installation and see if these issues still persist. I'll close this for now assuming it to be fixed. Feel free to open it again if that's not the case.
